Week4/word_central/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'site#home', as: :home

  get '/text_inspections/new', to: 'test_inspections#new'
  post '/text_inspections', to: 'test_inspections#create'

  get '/asciis/new', to: 'asciis#new'
  post '/asciis', to: 'asciis#create'

  get '/dummytexts/new', to: 'dummy_texts#new'
  post '/dummytexts', to: 'dummy_texts#create'
end

Week4/word_central/app/models/generate.rb
class Generate < ApplicationRecord
end

Week4/word_central/app/models/word_tool.rb
class WordTool < ApplicationRecord
  def self.count_words(words)
    frequencies = Hash.new(0)

    words.each { |word|
      frequencies[word] += 1
    }

    frequencies.sort_by {|word, count|
      count
    }.reverse[0..10]
  end
end

Week4/word_central/app/controllers/asciis_controller.rb
class AsciisController < ApplicationController
  def new
    render 'new'
  end

  def create
    @text = params[:ascii][:user_text]

    the_ascifier = Artii::Base.new(:font => 'alligator')

    @ascified = the_ascifier.asciify(@text)

    render 'results'
  end
end

Week4/word_central/app/controllers/dummy_texts_controller.rb
class DummyTextsController < ApplicationController
  def new
    render 'new'
  end

  def create
    @user_number = params[:dummy][:user_text]
    @user_choice = params[:dummy][:user_type]

    render 'results'
  end
end

Week4/word_central/app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    render 'home'
  end
end

Week4/word_central/app/controllers/test_inspections_controller.rb
class TestInspectionsController < ApplicationController
  def new
    render 'new'
  end

  def create
    @text = params[:text_inspection][:user_text]

    @word_count = @text.split(" ").length

    @frequencies = WordTool.count_words(@text.split(" "))

    @reading_time = (@word_count.to_f/275).round(2)

    render "results"
  end
end

Week4/word_central/app/helpers/asciis_helper.rb
module AsciisHelper
end

Week4/word_central/app/helpers/dummy_texts_helper.rb
module DummyTextsHelper
end

Week4/word_central/app/helpers/site_helper.rb
module SiteHelper
end

Week4/word_central/app/helpers/test_inspections_helper.rb
module TestInspectionsHelper
end

Week4/word_central/app/views/asciis/new.html.erb
<h1>Ascii</h1>

<form action='/asciis' method='post'>
  <div>
  <input type="hidden" name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <label for="ascii_user_text">Ascii It</label>
    <textarea name="ascii[user_text]" id="ascii_user_text"></textarea>
  </div>
  <button type="submit">Submit text</button>
</form>

Week4/word_central/app/views/asciis/results.html.erb
<pre><%= @ascified %></pre>

<%= link_to "Home", home_path %>

Week4/word_central/app/views/site/home.html.erb
<h1>Word Central</h1>
<p>Your destination for text utilities</p>

Week4/word_central/app/views/test_inspections/new.html.erb
<h1>Word Central</h1>
<h2>Submit text for inspection</h2>

<form action='/text_inspections' method='post'>
  <div>
  <input type="hidden" name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <label for="text_inspection_user_text">Text</label>
    <textarea name="text_inspection[user_text]" id="text_inspection_user_text"></textarea>
  </div>
  <button type="submit">Submit text</button>
</form>

Week4/word_central/app/views/test_inspections/results.html.erb
<h1>Results</h1>

<h3>Original text:</h3>
<p><%= @text %></p>

<h3>Word Count:</h3>
<p><%= @word_count %></p>

<h4>Est. Reading Time:</h4>
<p><%= @reading_time %> min</p>

<h4>Top 10 Words Used: </h4>
<p><%= @frequencies %></p>

<%= link_to "Home", home_path %>